### ISSUE TITLE
TypeError: Cannot use 'in' operator to search for 'enabled' in null

### ISSUE THREAD

**Issue by nareshbulusu** [octoherd/script-sync-branch-protections#5]
# Command used below (masked actual names)

```
npx @octoherd/script-sync-branch-protections \
  -T "${GITHUB_TOKEN}"
  -R "myorg/repo1"
  --template "myorg/repo-template"
```

# Error message below

```
ERROR  TypeError: Cannot use 'in' operator to search for 'enabled' in null
    at file:///Users/user1/.npm/_npx/9c37c62cde30630c/node_modules/@octoherd/script-sync-branch-protections/utils.js:52:19
    at file:///Users/user1/.npm/_npx/9c37c62cde30630c/node_modules/@octoherd/script-sync-branch-protections/utils.js:66:56
    at Array.map (<anonymous>)
    at mapValues (file:///user1/.npm/_npx/9c37c62cde30630c/node_modules/@octoherd/script-sync-branch-protections/utils.js:66:28)
    at file:///Users/user1/.npm/_npx/9c37c62cde30630c/node_modules/@octoherd/script-sync-branch-protections/utils.js:74:53
    at Array.map (<anonymous>)
    at mapValues (file:///user1/.npm/_npx/9c37c62cde30630c/node_modules/@octoherd/script-sync-branch-protections/utils.js:74:39)
    at mapValues (file:///Users/user1/.npm/_npx/9c37c62cde30630c/node_modules/@octoherd/script-sync-branch-protections/utils.js:76:24)
    at mapValues (file:///Users/user1/.npm/_npx/9c37c62cde30630c/node_modules/@octoherd/script-sync-branch-protections/utils.js:76:24)
    at protectionResponseDataToUpdateParameters (file:///Users/user1/.npm/_npx/9c37c62cde30630c/node_modules/@octoherd/script-sync-branch-protections/utils.js:47:22)
```

**Comment by gr2m** [comment]
Hi Naresh,

it's hard to debug for me without having access to your `"myorg/repo-template"` repo.

Could you please clone this repository to your local machine, install dependencies, then run

```
node cli.js \
  -T "${GITHUB_TOKEN}" \
  -R "myorg/repo1" \
  --template "myorg/repo-template"
```

And see if it reproduces the problem? If it does, can you please open the `utils.js` file and do the following change

```diff
- if ("enabled" in value) return value.enabled;
+ if (value === null) console.log({ key, data });
+ if ("enabled" in value) return value.enabled;
```

That should give us some more information of what kind of response data we are not handling properly

**Comment by nareshbulusu** [comment]
> Hi Naresh,
> 
> it's hard to debug for me without having access to your `"myorg/repo-template"` repo.
> 
> Could you please clone this repository to your local machine, install dependencies, then run
> 
> ```
> node cli.js \
>   -T "${GITHUB_TOKEN}" \
>   -R "myorg/repo1" \
>   --template "myorg/repo-template"
> ```
> 
> And see if it reproduces the problem? If it does, can you please open the `utils.js` file and do the following change
> 
> ```diff
> - if ("enabled" in value) return value.enabled;
> + if (value === null) console.log({ key, data });
> + if ("enabled" in value) return value.enabled;
> ```
> 
> That should give us some more information of what kind of response data we are not handling properly

@gr2m 
Hi Gregor, Thanks for looking into this. As requested I have reproduced the problem with cli.js and captured additional info, please see below

`
nareshkumarbulusus-MacBook-Pro:script-sync-branch-protections nareshkumar.bulusu$ node cli.js \
>   -T "${GITHUB_TOKEN}" \
>   -R "sede-x/iiac-sync-policies-test1" \
>   --template "sede-x/shell-innersource-iac-terraform"

Running @octoherd/cli v3.3.0 (@octoherd/octokit v2.3.1, Node.js: v14.16.1, darwin x64)

 INFO  Loading repositories ...
.
 INFO  Running on sede-x/iiac-sync-policies-test1 ...
{
  key: 'parent',
  data: {
    url: 'https://api.github.com/repos/sede-x/shell-innersource-iac-terraform/branches/main/protection',
    required_status_checks: {
      url: 'https://api.github.com/repos/sede-x/shell-innersource-iac-terraform/branches/main/protection/required_status_checks',
      strict: true,
      contexts: [],
      contexts_url: 'https://api.github.com/repos/sede-x/shell-innersource-iac-terraform/branches/main/protection/required_status_checks/contexts'
    },
    required_pull_request_reviews: {
      url: 'https://api.github.com/repos/sede-x/shell-innersource-iac-terraform/branches/main/protection/required_pull_request_reviews',
      dismiss_stale_reviews: false,
      require_code_owner_reviews: true,
      dismissal_restrictions: [Object]
    },
    enforce_admins: {
      url: 'https://api.github.com/repos/sede-x/shell-innersource-iac-terraform/branches/main/protection/enforce_admins',
      enabled: true
    },
    required_linear_history: { enabled: true },
    allow_force_pushes: { enabled: false },
    allow_deletions: { enabled: false }
  }
}
 ERROR  TypeError: Cannot use 'in' operator to search for 'enabled' in null
    at file:///Users/nareshkumar.bulusu/src/github/script-sync-branch-protections/utils.js:53:19
    at file:///Users/nareshkumar.bulusu/src/github/script-sync-branch-protections/utils.js:67:56
    at Array.map (<anonymous>)
    at mapValues (file:///Users/nareshkumar.bulusu/src/github/script-sync-branch-protections/utils.js:67:28)
    at file:///Users/nareshkumar.bulusu/src/github/script-sync-branch-protections/utils.js:75:53
    at Array.map (<anonymous>)
    at mapValues (file:///Users/nareshkumar.bulusu/src/github/script-sync-branch-protections/utils.js:75:39)
    at mapValues (file:///Users/nareshkumar.bulusu/src/github/script-sync-branch-protections/utils.js:77:24)
    at mapValues (file:///Users/nareshkumar.bulusu/src/github/script-sync-branch-protections/utils.js:77:24)
    at protectionResponseDataToUpdateParameters (file:///Users/nareshkumar.bulusu/src/github/script-sync-branch-protections/utils.js:47:22)

--------------------------------------------------------------------------------

`

**Comment by nareshbulusu** [comment]
@gr2m I tried this script on my personal GH account and it worked flawlessly. The issue seems to be due to some restrictions on GitHub APIs at my org level. For now, I am closing this issue as there is no evidence to suggest that this ssue is due to the script. However, some additional logging would be nice.

**Comment by gr2m** [comment]
> However, some additional logging would be nice

agreed. I'll look into it

**Comment by gr2m** [comment]
I think I can properly fix this issue

**Comment by gr2m** [comment]
The existing `typeof value !== "object"` check wasn't enough because `typeof null` is `"object"`, too

**Comment by nareshbulusu** [comment]
> The existing `typeof value !== "object"` check wasn't enough because `typeof null` is `"object"`, too. Can you try again with the new version? Should be out any moment

@gr2m Thank you very much! I'll give it a try and provide feedback here.
